# Generated by Django 3.1.3 on 2020-11-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viberuser',
            name='subscribed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
