# Generated by Django 3.1.3 on 2020-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberapi', '0003_auto_20201122_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viberuser',
            name='bitrix_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
