# Generated by Django 3.1.3 on 2020-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('bitrix_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('language_code', models.CharField(max_length=20)),
            ],
        ),
    ]
